#!/bin/bash
# System configuration: hostname, admin user, SSH, network, fstab.

config_ask_hostname() {
    whiptail --title "Hostname" \
        --inputbox "Enter a hostname for this cluster node:" \
        8 52 "cluster-node-1" 3>&1 1>&2 2>&3
}

config_ask_username() {
    whiptail --title "Admin User" \
        --inputbox "Enter the admin username:" \
        8 52 "admin" 3>&1 1>&2 2>&3
}

config_ask_password() {
    local pass1 pass2
    while true; do
        pass1=$(whiptail --title "Password" \
            --passwordbox "Enter password for the admin user:" \
            8 52 3>&1 1>&2 2>&3)
        pass2=$(whiptail --title "Password" \
            --passwordbox "Confirm password:" \
            8 52 3>&1 1>&2 2>&3)
        [[ "$pass1" == "$pass2" ]] && break
        whiptail --title "Error" --msgbox "Passwords do not match. Try again." 8 52
    done
    echo "$pass1"
}

config_ask_ssh_key() {
    whiptail --title "SSH Public Key (optional)" \
        --inputbox "Paste an SSH public key to add to authorized_keys.\nLeave empty to skip." \
        10 72 "" 3>&1 1>&2 2>&3
}

config_ask_network() {
    local mode
    mode=$(whiptail --title "Network" \
        --menu "Select network configuration mode:" 12 52 2 \
        "dhcp"   "DHCP (automatic)" \
        "static" "Static IP address" \
        3>&1 1>&2 2>&3)

    if [[ "$mode" == "static" ]]; then
        local iface ip gw dns
        iface=$(whiptail --title "Interface" \
            --inputbox "Interface name (e.g. eth0, ens3):" 8 52 "eth0" 3>&1 1>&2 2>&3)
        ip=$(whiptail --title "IP Address" \
            --inputbox "IP address with prefix length (e.g. 192.168.1.10/24):" 8 52 "" 3>&1 1>&2 2>&3)
        gw=$(whiptail --title "Gateway" \
            --inputbox "Default gateway:" 8 52 "" 3>&1 1>&2 2>&3)
        dns=$(whiptail --title "DNS" \
            --inputbox "DNS servers (space-separated):" 8 52 "8.8.8.8 8.8.4.4" 3>&1 1>&2 2>&3)
        echo "static:${iface}:${ip}:${gw}:${dns}"
    else
        echo "dhcp"
    fi
}

# Applies all configuration to the installed root.
# Usage: config_apply <root> <hostname> <username> <password> <ssh_key> <network>
config_apply() {
    local root="$1" hostname="$2" username="$3" password="$4" ssh_key="$5" network="$6"

    _config_hostname    "$root" "$hostname"
    _config_user        "$root" "$username" "$password"
    _config_ssh_key     "$root" "$username" "$ssh_key"
    _config_network     "$root" "$network"
    _config_fstab       "$root"
    _config_timezone    "$root"
    _config_services    "$root"
}

_config_hostname() {
    local root="$1" hostname="$2"
    echo "$hostname" > "$root/etc/hostname"
    # Append /etc/hosts entry only if it doesn't already exist.
    grep -q "127.0.1.1" "$root/etc/hosts" 2>/dev/null \
        || echo "127.0.1.1 $hostname" >> "$root/etc/hosts"
}

_config_user() {
    local root="$1" username="$2" password="$3"
    # Add user with docker and libvirt groups (present in the image).
    chroot "$root" useradd -m -s /bin/bash -G sudo,docker,libvirt "$username" 2>/dev/null \
        || chroot "$root" useradd -m -s /bin/bash "$username"
    echo "${username}:${password}" | chroot "$root" chpasswd
}

_config_ssh_key() {
    local root="$1" username="$2" ssh_key="$3"
    [[ -z "$ssh_key" ]] && return 0

    local uid
    uid=$(chroot "$root" id -u "$username" 2>/dev/null || echo 1000)
    local ssh_dir="$root/home/$username/.ssh"
    mkdir -p "$ssh_dir"
    echo "$ssh_key" >> "$ssh_dir/authorized_keys"
    chmod 700 "$ssh_dir"
    chmod 600 "$ssh_dir/authorized_keys"
    chown -R "${uid}:${uid}" "$ssh_dir"
}

_config_network() {
    local root="$1" network="$2"
    local netd_dir="$root/etc/systemd/network"
    mkdir -p "$netd_dir"

    if [[ "$network" == "dhcp" ]]; then
        cat > "$netd_dir/20-wired.network" <<'EOF'
[Match]
# Match all wired interfaces.
Name=en* eth*

[Network]
DHCP=yes
EOF
    else
        IFS=: read -r _ iface ip gw dns <<< "$network"
        cat > "$netd_dir/20-static.network" <<EOF
[Match]
Name=$iface

[Network]
Address=$ip
Gateway=$gw
DNS=$dns
EOF
    fi
}

_config_fstab() {
    local root="$1"
    # Root (/) is managed by ABRoot's initramfs hook (root=UUID= kernel param).
    # fstab only declares /boot (ext4), /boot/efi (vfat), and /var (btrfs).
    local efi_uuid boot_uuid var_uuid
    efi_uuid=$(blkid  -s UUID -o value "$(findfs LABEL=vos-efi  2>/dev/null)")
    boot_uuid=$(blkid -s UUID -o value "$(findfs LABEL=vos-boot 2>/dev/null)")
    var_uuid=$(blkid  -s UUID -o value "$(findfs LABEL=vos-var  2>/dev/null)")

    cat > "$root/etc/fstab" <<EOF
# /etc/fstab — generated by simple-cluster-installer.
# Root (/) is managed by ABRoot; it is not listed here.
UUID=$boot_uuid  /boot      ext4   defaults          0  2
UUID=$efi_uuid   /boot/efi  vfat   umask=0077        0  2
UUID=$var_uuid   /var       btrfs  defaults,noatime  0  0
EOF
}

_config_timezone() {
    local root="$1"
    chroot "$root" ln -sf /usr/share/zoneinfo/UTC /etc/localtime 2>/dev/null || true
}

_config_services() {
    local root="$1"
    # Ensure SSH is enabled (sshd may be named differently depending on the image).
    chroot "$root" systemctl enable ssh.service   2>/dev/null || \
    chroot "$root" systemctl enable sshd.service  2>/dev/null || true
    # Enable networkd/resolved for the network config written above.
    chroot "$root" systemctl enable systemd-networkd.service  2>/dev/null || true
    chroot "$root" systemctl enable systemd-resolved.service  2>/dev/null || true
}
